### ISSUE TITLE
Milestone 3 Feedback

### ISSUE THREAD

**Issue by ghost** [UBC-MDS/obesity-explorer-R#61]
Hey Group 1,

You've made some excellent progress this milestone and I'm really impressed with all the improvements you've made. I think this new layout with plots split on different tabs makes it a lot easier to sift through the various info being provided on the dashboard. All of the controls are also clearly matched with their corresponding components. In terms of potential improvements, I have only a few minor points:
- global filters don't seem to apply to second tab, but probably should
- might consider making trend lines a bit thinner, world trendlines would also be nice (with different styling, e.g. dotted/dashed)
- missing data in scatter still. If you don't have this data consider just printing text on the plot that says 'No Data Available for this Selection', or similar
- fixed z-scale on map/bar plot would be better for seeing changes in single countries across years
- other plots have year label but scatterplot doesn't. Consider adding one for consistency

Good luck with your final milestone!

**Comment by tanmaysharma19** [comment]
Hey @gubbelcn,
Thank you for the feedback. Below is a task list to address your suggestions. 
- [x] global filters don't seem to apply to second tab, but probably should: Addressed in #64 
- [x] might consider making trend lines a bit thinner, world trendlines would also be nice (with different styling, e.g. dotted/dashed): Addressed in #56 and #77 respectively.
- [x] missing data in scatter still. If you don't have this data consider just printing text on the plot that says 'No Data Available for this Selection', or similar: Addressed in #55 
- [x] fixed z-scale on map/bar plot would be better for seeing changes in single countries across years: Addressed in #57  
- [x] other plots have year label but scatterplot doesn't. Consider adding one for consistency: Addressed in #30
